### ISSUE TITLE
Kanban board set up

### ISSUE THREAD

**Issue by haftamudesta** [haftamudesta/Ruby-Capstone-Project#24]
https://github.com/haftamudesta/Ruby-Capstone-Project/projects/1

In this project, we are two team members @haftamudesta  and @CarlosIgreda
@haftamudesta  is assigned to Team number #2 and group tasks
@CarlosIgreda  is assigned to team number #1 and group tasks

**Comment by Gambit142** [comment]
Hi @haftamudesta @CarlosIgreda 👋, 

Good job so far!

## Highlights
- Created a kanban board that is identical to the sample ✔️ 
- Tasks are distributed in a fair way ✔️ 
- Each card has a title and point ✔️ 
- Each card is assigned to a member ✔️ 

You still need to work on some issues to go to the next project, but you are almost there!

## Required Changes ♻️

- [ ] Kindly add a group card for this project requirement 💻 :

- All Item class properties visible in the diagram should be defined and set up in the constructor method. Exception: properties for the 1-to-many relationships should NOT be set in the constructor method. Instead, they should have a custom setter method created.

- [ ] I noticed that all cards don't have a description. Kindly add a description to each card on the Kanban board 👍 😎 

- [ ] For `Team Member 1`, the following cards are missing 😄:

- All Book class properties visible in the diagram should be defined and set up in the constructor method.
- All Label class properties visible in the diagram should be defined and set up in the constructor method.
- The following options should be available:
  - List all books
  - List all labels (e.g. 'Gift', 'New')
  - Add a book

- [ ] For `Team Member 2`, the following cards are missing 😎 :

- All MusicAlbum class properties visible in the diagram should be defined and set up in the constructor method.
- All Genre class properties visible in the diagram should be defined and set up in the constructor method.
- The following options should be available:
  - List all music albums
  - List all genres (e.g 'Comedy', 'Thriller')
  - Add a music album

- [ ] I understand that the team is made up of two members and the project requirements state that you should share the task that should be assigned to **_Team Member 3_**. Although you share the tasks in the kanban board, the following cards are missing for **_Team member 3_** tasks 💻 🖱️:
- All Game class properties visible in the diagram should be defined and set up in the constructor method.
- All Author class properties visible in the diagram should be defined and set up in the constructor method.
- The following options should be available:
  - List of games
  - List all authors (e.g. 'Stephen King')
  - Add a game 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by ghost** [comment]
Hi Team , 

You can ahead with your project 🎉 

<img src="https://media1.giphy.com/media/ExSXXwQmCSMWKor0qb/giphy.gif"/>

## Highlights

- [ ] The board is well set up ✔️

## Optional suggestions

N/A
